dicionario_materiais = {
	'PF2510': 'Parafuso 2.5x10', 
	'PF2516': 'Parafuso 2.5x16', 
	'PF3012O': 'Parafuso 3.0x12 oxidado', 
	'PF3510': 'Parafuso 3.5x10', 
	'PF3512': 'Parafuso 3.5x12', 
	'PF3535': 'Parafuso 3.5x35', 
	'PF3540': 'Parafuso 3.5x40', 
	'PF4025': 'Parafuso 4.0x25', 
	'PF4025O': 'Parafuso 4.0x25 oxidado', 
	'PF4030': 'Parafuso 4.0x30', 
	'PF4050': 'Parafuso 4.0x50', 
	'PF5025': 'Parafuso 5.0x25', 
	'PN10': 'Pino F-10', 
	'PN15': 'Pino F-15', 
	'PN20': 'Pino F-20', 
	'PN25': 'Pino F-25', 
	'PN30': 'Pino F-30', 
	'PLS01': 'Sapata Marrom', 
	'PLS02': 'Sapata Marfim', 
	'PLS03': 'Mini Sapata Marrom', 
	'PLS04': 'Mini Sapata Marfim', 
	'PLS05': 'Mini Sapata Branca', 
	'PLPB': 'Porta Bandeja', 
	'PLPC': 'Porta Carretel', 
	'PXGOV': 'Puxador Guarujá Ouro Verde', 
	'PXPCR': 'Puxador Parati Cerejeira', 
	'PXPMF': 'Puxador Parati Marfim', 
	'PXPMR': 'Puxador Parati Marrom', 
	'PLGPP': 'Gaveta PP',
	'PLPP' : 'Bandeja PP Plástica',
	'PLCRP': 'Corrediça Plástica', 
	'PLALB': 'Alça Baú', 
	'MTDCB': 'Dobradiça Cabeçote', 
	'MTDTP': 'Dobradiça Tampo', 
	'MTDPT': 'Dobradiça Porta', 
	'MTFRL': 'Fecho Rolete', 
	'MTD14': 'Dobradiça 1.1/4', 
	'MTC2F': 'Cantoneira 2f', 
	'MTTBA': 'Trinco Baú', 
	'MTPBS': 'Pino Base', 
	'CXGTD': 'Embalagem Gabinete Tradicional Desmontado', 
	'CXGTM': 'Embalagem Gabinete Tradicional Montado', 
	'CXGLD': 'Embalagem Gabinete Luxo Desmontado', 
	'CXGLM': 'Embalagem Gabinete Luxo Montado', 
	'CXMS': 'Embalagem Mesa', 
	'CXBS': 'Embalagem Caixa-Base', 
	'CXBA': 'Embalagem Baú', 
	'CXBC': 'Embalagem Bancada', 
	'CXEL': 'Embalagem Elgin',
	'CAVI': 'Cavilha de Madeira'
	}